spring:
  application:
    name: api-gateway

  config:
#    fail-fast
    import: "configserver:"

#  cloud:
#    config:
#      uri: http://config.platform:9000
  cloud:
    config:
      uri: http://localhost:9000